openapi: 3.0.1
info:
  title: Device Management API
  description: API для управления устройствами в экосистеме умного дома
  version: 1.0.0

paths:
  /devices:
    post:
      summary: Добавление нового устройства
      description: Регистрирует новое устройство в системе.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                serial_number:
                  type: string
                  example: "ABC123456"
                type_id:
                  type: string
                  example: "thermostat"
                house_id:
                  type: string
                  example: "house123"
                status:
                  type: string
                  enum: ["online", "offline"]
                  example: "offline"
              required:
                - serial_number
                - type_id
                - house_id
      responses:
        201:
          description: Устройство успешно добавлено
        400:
          description: Ошибка валидации запроса
        500:
          description: Внутренняя ошибка сервера

  /devices/{deviceId}/status:
    patch:
      summary: Обновление состояния устройства
      description: Обновляет статус устройства.
      parameters:
        - in: path
          name: deviceId
          schema:
            type: string
          required: true
          description: Идентификатор устройства
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: ["online", "offline"]
                  example: "online"
              required:
                - status
      responses:
        200:
          description: Статус устройства успешно обновлён
        404:
          description: Устройство не найдено
        500:
          description: Внутренняя ошибка сервера


